package string;

public class Test {

String s1 = "Marlabs";

public static void main(String [] args)

{
	
	String s1 = "Marlabs";
	s1.concat("Innovations");
	//System.out.println(s1);
	//When we print reference variable in java toString() method present in object class is overridden with toString method in String class
	System.out.println(s1.toString());
	
	StringBuffer sb1 = new StringBuffer();
	sb1.append("Innovations");
	//System.out.println(sb1);
	System.out.println(sb1.toString());
	//When we print reference variable in java toString() method present in object class is overridden with toString method in StringBuffer class
	
}

}

/*Note:toString() method returns class-name@hashcode. Hashcode is hexadecimal number generated by JVM to uniquely identify object
*Our class toString() method is executed after overriding toString() method present in parent class called object

*/
